apiVersion: v1
kind: Pod
metadata:
  name: portfolio
  namespace: default
  labels:
    app: portfolio-stack
    component: frontend
spec:
  containers:
  - name: portfolio
    image: ghcr.io/matheusmacias/macias-portfolio:latest
    ports:
    - containerPort: 3000
      hostPort: 3000
    envFrom:
    - secretRef:
        name: portfolio-credentials
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app: portfolio-stack
    component: nginx
spec:
  containers:
  - name: nginx
    image: docker.io/library/nginx:alpine
    ports:
    - containerPort: 80
      hostPort: 80
    - containerPort: 443
      hostPort: 443
    volumeMounts:
    - name: letsencrypt
      mountPath: /etc/letsencrypt
    - name: nginx-site-config
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  - name: certbot
    image: docker.io/nbraun1/certbot:latest
    ports:
    - containerPort: 8080
      hostPort: 8080
    env:
    - name: ENABLE_MULTI_CERTIFICATES
      value: "1"
    - name: MULTI_CERTIFICATES_INI_FILE
      value: "/etc/certbot/multi-certificates.ini"
    volumeMounts:
    - name: letsencrypt
      mountPath: /etc/letsencrypt
    - name: certbot-config
      mountPath: /etc/certbot/multi-certificates.ini
      subPath: multi-certificates.ini
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

  volumes:
  - name: nginx-site-config
    configMap:
      name: nginx-site-config
  - name: certbot-config
    configMap:
      name: certbot-multi-config
  - name: letsencrypt
    hostPath:
      path: /etc/letsencrypt
      type: DirectoryOrCreate

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certbot-multi-config
data:
  multi-certificates.ini: |
    [DEFAULT]
    EMAIL=matheusmacias3@gmail.com
    CRON=0 2 * * *
    HTTP01_PORT=8080
    STAGING=0
    VERBOSE=1

    [macias-domain]
    DOMAINS=macias.one,www.macias.one
    CERT_NAME=macias-one

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-site-config
  namespace: default
data:
  default.conf: |
    upstream portfolio {
        server portfolio:3000;
        keepalive 64;
    }

    # HTTP - Redirect to HTTPS
    server {
        listen 80;
        server_name macias.one www.macias.one;

        # ACME challenge for Let's Encrypt
        location /.well-known/acme-challenge/ {
            proxy_pass http://localhost:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Redirect to HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    # HTTPS
    server {
        listen 443 ssl http2;
        server_name macias.one www.macias.one;

        ssl_certificate /etc/letsencrypt/live/macias-one/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/macias-one/privkey.pem;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;
        ssl_prefer_server_ciphers on;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;

        # Gzip
        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;

        # Upload size limit
        client_max_body_size 10M;

        # WebSocket support for Socket.io
        location /api/socketio {
            proxy_pass http://portfolio;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 86400;
            proxy_send_timeout 86400;
        }

        location / {
            proxy_pass http://portfolio;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header Connection "";

            # Cache static assets
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
                proxy_pass http://portfolio;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Connection "";

                expires 1y;
                add_header Cache-Control "public, immutable";
            }
        }
    }
